[[redirects]]
  from = "http://livewebstudios.com/*"
  to = "https://livewebstudios.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.livewebstudios.com/*"
  to = "https://livewebstudios.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/forms/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
